#!/usr/bin/env php
<?php
define('NAGIOS_RETURN_OK',       0);
define('NAGIOS_RETURN_WARNING',  1);
define('NAGIOS_RETURN_CRITICAL', 2);
define('NAGIOS_RETURN_UNKNOWN',  3);
function usage() {
    $msg = <<<USG

check_udp_port - Nagios plugin to check udp ports

Usage:
    check_udp_ports <server> <port>

Parameters:

    <server>
        server hostname

    <port>
        server port
        
USG;
    echo $msg;
    exit;
}
if ($argc < 3 || in_array($argv[1], array('-h', '--help'))) {
    usage();
}
// parameters
$server	 	= $argv[1];
$port		= $argv[2];
$ncpath 		= '/usr/bin/nc';
$command = $ncpath.' -4zu '.$server.' '.$port;
$result = shell_exec($command);
if(empty($result)){
	fwrite(STDERR, "CRITICAL: Server isnt responding with data.\n");
	die(NAGIOS_RETURN_CRITICAL);	
}else{
	fwrite(STDERR, "OK: Server is responding with data.\n");
	die(NAGIOS_RETURN_OK);	
}
?>